### ISSUE TITLE
Shibboleth login fails on Python 3.12 with uWSGI: uwsgi._Input has no attribute 'encode'

### ISSUE THREAD

**Issue by daelmaselli** [indico/indico#7213]
## Description

After upgrading Indico from 3.3.7 to 3.3.9 and Python from 3.12.11 to 3.12.12 using:

```bash
indico setup upgrade-python
```

Shibboleth login started failing with:

```text
AttributeError: 'uwsgi._Input' object has no attribute 'encode'
```

## Traceback excerpt

```python
File ".../flask_multipass/providers/shibboleth.py", line XX, in _fix_data
    v = v.encode('latin1').decode('utf-8')
AttributeError: 'uwsgi._Input' object has no attribute 'encode'
```

## Environment

* **Indico:** 3.3.9
* **Python:** 3.12.12 (managed via `indico setup upgrade-python`)
* **Flask-Multipass:** 0.11
* **uWSGI:** 2.0.31
* **Authentication:** Shibboleth (via WSGI environ)

## Problem

Some values coming from the WSGI environment are not strings but `uwsgi._Input` objects.
The `_fix_data()` function in `flask_multipass.providers.shibboleth` assumes `v` is always a string and calls `.encode()`, causing the error.

## Temporary Workaround

We patched `_fix_data()` as follows:

```python
def _fix_data(iter_, fix_encoding):
    for k, v in iter_:
        if fix_encoding and isinstance(v, str):
            try:
                # Values coming from WSGI environ may be UTF-8 bytes mis-decoded as Latin-1
                v = v.encode('latin1').decode('utf-8')
            except UnicodeError:
                pass
        else:
            v = str(v)
        yield k.lower(), v
```

After applying this change and restarting uWSGI, Shibboleth login works correctly.

## Additional Notes

This seems to be an interaction issue between uWSGI and Python 3.12 when passing WSGI environ values.
I wanted to report it in case this combination is still expected to be supported or should be documented as unsupported.
